### ISSUE TITLE
release for php 8.2 compatibility?

### ISSUE THREAD

**Issue by rbro** [Skrol29/opentbs#30]
Would it be possible to do a release for the PHP 8.2 compatibility updates that were made?  Thanks for your help.

**Comment by Skrol29** [comment]
Yep, it will be released soon…

**Comment by tim-pearce** [comment]
I downloaded this version and still get errors on PHP 8.2
Creation of dynamic property clsOpenTBS::$ArchHnd is deprecated
Line 8050 of File /usr/local/www/apache24/data/Jethro/include/tbs_plugin_opentbs.php
Similar for $CdInfo, $CdFileLst and many more.

**Comment by Skrol29** [comment]
It seems that you are using an error handler function because those messages you have are supposed to be 
suppressed by the Error Control Operators `@` at line 181.

However, there will be a fix soon in order to strengthen the PHP 8.2 compatibility, and this should fix the the error messages you have.
