### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by montac** [Skrol29/opentbs#7]
Hi,

Can you give an example of how to add a new slide to the archive with the code below from the documentation please ?

I dont Inderstand what the variable `$Data` should contain.

```php
// OpenTBS >= 1.6.0
$TBS->Plugin(OPENTBS_ADDFILE, $Name, $Data, $DataType=OPENTBS_STRING, $Compress=true);
```

Thank you.

**Comment by Skrol29** [comment]
Hello,

Adding a new slide in a PPTX or an ODP is not as simple as adding a file in the archive. There is lot of modification in other XML files in order to be compliant with the format.

Thus, OpenTBS has no feature for adding a new slide in a presentation for now. But it can delete existing slides. So a work around is to create optional slides in your template and delete unwanted slides during the merging.

**Comment by montac** [comment]
Thank you for these clarifications.
